version: '3.8'

services:
  torbox-media-center:
    image: ghcr.io/torbox-app/torbox-media-center:latest
    container_name: torbox-media-center
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ${MOUNT_HOST_PATH:-/mnt/torbox}:/torbox:rshared
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
